// ui/src/routes/matchmaking/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';
  import { goto } from '$app/navigation';

  let playerId = '';
  let isInQueue = false;
  let queueSocket = null;

  function getCookie(name) {
    const value = `; ${document.cookie}`;
    const parts = value.split(`; ${name}=`);
    if (parts.length === 2) {
      const cookieValue = parts.pop()?.split(';').shift();
      return cookieValue;
    }
    return null;
  }

  function findMatch() {
    if (isInQueue) return;
    
    isInQueue = true;
    
    const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${wsProtocol}//${window.location.hostname}/ws`;
    
    queueSocket = new WebSocket(wsUrl);
    
    queueSocket.onopen = () => {
      queueSocket.send(JSON.stringify({
        type: 'queue',
        from: playerId
      }));
    };

    queueSocket.onmessage = (event) => {
      const msg = JSON.parse(event.data);
      
      if (msg.type === 'match_found') {
        isInQueue = false;
        const gameId = msg.gameId;
        
        queueSocket.close();
        queueSocket = null;
        
        goto(`/games?game=${gameId}`);
      }
    };

    queueSocket.onerror = (error) => {
      console.error('Queue WebSocket error:', error);
      isInQueue = false;
      queueSocket = null;
    };

    queueSocket.onclose = () => {
      isInQueue = false;
      queueSocket = null;
    };
  }

  onMount(() => {
    if (browser) {
      playerId = getCookie('playerId');
      if (!playerId) {
        goto('/');
        return;
      }
      findMatch();
    }
  });
</script>

<div class="container">
  <div class="queue-status">
    <div class="queue-spinner"></div>
    <p>Finding match...</p>
  </div>
</div>

<style>
  :global(body) { 
    background: #121213; 
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  .container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
  }

  .queue-status {
    background-color: rgba(0, 0, 0, 0.9);
    padding: 30px;
    border-radius: 12px;
    text-align: center;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
    backdrop-filter: blur(8px);
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .queue-status p {
    color: white;
    margin: 15px 0 0;
    font-size: 1.2rem;
    font-weight: 500;
    letter-spacing: 0.5px;
  }

  .queue-spinner {
    width: 40px;
    height: 40px;
    border: 3px solid rgba(255, 255, 255, 0.1);
    border-top-color: #538d4e;
    border-radius: 50%;
    margin: 0 auto;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

// ui/src/pages/Matchmaking.tsx
import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const Matchmaking: React.FC = () => {
  const navigate = useNavigate();
  useEffect(() => {
    const player = JSON.parse(localStorage.getItem('player') || 'null');
    if (!player || !player.id) {
      window.location.href = '/';
      return;
    }
    const ws = new WebSocket(
      window.location.protocol === 'https:'
        ? `wss://${window.location.host}/ws/matchmaking`
        : `ws://${window.location.host}/ws/matchmaking`
    );
    ws.onopen = () => {
      ws.send(JSON.stringify({ type: 'join', player_id: player.id }));
    };
    ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data);
        if (msg.type === 'match_found' && msg.game_id) {
          ws.close();
          navigate(`/game/${msg.game_id}`);
        }
      } catch {}
    };
    ws.onerror = () => {
      // Optionally handle error
    };
    return () => {
      ws.close();
    };
  }, [navigate]);

  return (
    <div style={{
      width: '100vw',
      height: '100vh',
      background: '#121213',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      fontFamily: `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif`,
    }}>
      <div style={{
        backgroundColor: 'rgba(0,0,0,0.9)',
        padding: 30,
        borderRadius: 12,
        textAlign: 'center',
        boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
        backdropFilter: 'blur(8px)',
        border: '1px solid rgba(255,255,255,0.1)',
        maxWidth: 500,
      }}>
        <div style={{
          width: 40,
          height: 40,
          border: '3px solid rgba(255,255,255,0.1)',
          borderTopColor: '#538d4e',
          borderRadius: '50%',
          margin: '0 auto',
          animation: 'spin 1s linear infinite',
        }}
        className="queue-spinner"
        />
        <p style={{
          color: 'white',
          margin: '15px 0 0',
          fontSize: '1.2rem',
          fontWeight: 500,
          letterSpacing: 0.5
        }}>
          Finding match...
        </p>
      </div>
      {/* Spinner animation keyframes */}
      {/* TODO: Move spinner CSS to a stylesheet for scalability */}
      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default Matchmaking;
